<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Release</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <OutputType>Library</OutputType>
    <RootNamespace>Telex</RootNamespace>
    <AssemblyName>Telex</AssemblyName>
    <TargetFrameworkVersion>v3.5</TargetFrameworkVersion>
    <LangVersion>latest</LangVersion>
    <GameDir Condition=" '$(GameDir)' == '' ">/home/khill/.local/share/Steam/steamapps/common/Cities_Skylines</GameDir>
    <ManagedDir>$(GameDir)/Cities_Data/Managed</ManagedDir>
    <OutputPath>../../build/</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="mscorlib">
      <HintPath>$(ManagedDir)/mscorlib.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="System">
      <HintPath>$(ManagedDir)/System.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Core">
      <HintPath>$(ManagedDir)/System.Core.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="ICities">
      <HintPath>$(ManagedDir)/ICities.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(ManagedDir)/UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(ManagedDir)/Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="ColossalManaged">
      <HintPath>$(ManagedDir)/ColossalManaged.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="**\*.cs" />
  </ItemGroup>
</Project>
